environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
#

build_script:
  - gradlew build --info
#

# Add other jars maybe?
artifacts:
  - path: 'build\libs\Kotlin-CN-1.0.0-release.jar'
    name: lib
#
